# Generated by Django 5.1.1 on 2025-01-12 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_ad_image_generator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similaradvert',
            name='advert',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('error', 'Ошибка'), ('completed', 'Выполнена')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket_name', models.CharField(max_length=255)),
                ('copy_count', models.PositiveIntegerField()),
                ('delete_extra_files', models.BooleanField(default=False)),
                ('messages', models.JSONField(default=list)),
                ('task_type', models.CharField(choices=[('unique', 'Уникализация'), ('check', 'Проверка')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Advert',
        ),
        migrations.DeleteModel(
            name='SimilarAdvert',
        ),
    ]
