# Generated by Django 5.1.1 on 2025-01-14 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_ad_image_generator', '0002_remove_similaradvert_advert_task_delete_advert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='bucket_name',
            field=models.CharField(max_length=255, verbose_name='Имя бакета'),
        ),
        migrations.AlterField(
            model_name='task',
            name='copy_count',
            field=models.PositiveIntegerField(verbose_name='Количество уникализированных копий'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='delete_extra_files',
            field=models.BooleanField(default=False, verbose_name='Удалить лишние файлы в папках бакета'),
        ),
        migrations.AlterField(
            model_name='task',
            name='messages',
            field=models.JSONField(default=list, verbose_name='Сообщения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('error', 'Ошибка'), ('completed', 'Выполнена')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('unique', 'Уникализация'), ('check', 'Проверка')], max_length=10, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
